pg:
  host: 162.14.115.114
  user: cill
  passwd: 12345678
  db_name: test
  port: 5432
access:
  host: 127.0.0.1
  port: 8080
meta:
  host: 127.0.0.1
  port: 3000
data:
  host: 127.0.0.1
  port: 3001
log_level: "debug"
